# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_list_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_no', models.CharField(max_length=30)),
                ('course_syllabus', models.CharField(max_length=500, null=True)),
                ('course_additional_info', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMetarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_no', models.CharField(max_length=20, null=True)),
                ('courseWeek', models.IntegerField(null=True)),
                ('metarialNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Course_list_model')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('option4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=300, null=True)),
                ('question', models.CharField(max_length=300, null=True)),
                ('option1', models.CharField(max_length=50, null=True)),
                ('option2', models.CharField(max_length=50, null=True)),
                ('option3', models.CharField(max_length=50, null=True)),
                ('option4', models.CharField(max_length=50, null=True)),
                ('answerField', models.IntegerField(null=True)),
                ('extraOption', models.CharField(max_length=50, null=True)),
                ('extraAnswerField', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizNo', models.CharField(max_length=50)),
                ('questionList', models.ManyToManyField(blank=True, null=True, to='post.QuizQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.CourseMetarial')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="person's first name")),
                ('password', models.CharField(max_length=30)),
                ('crsToTake', models.ManyToManyField(blank=True, null=True, to='post.CourseMetarial')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_pass', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='registrationdate',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Student'),
        ),
        migrations.AddField(
            model_name='course_list_model',
            name='instructors',
            field=models.ManyToManyField(to='post.Teacher_model'),
        ),
    ]
