# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160429_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsection',
            name='questionList',
        ),
        migrations.DeleteModel(
            name='QuizSection',
        ),
    ]
