# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160429_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='crsToTake',
            field=models.ManyToManyField(blank=True, to='post.CourseMetarial'),
        ),
    ]
