# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsection',
            name='weekCount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Week'),
        ),
    ]
