# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_quizquestion_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='extraOption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizsection',
            name='questionList',
            field=models.ManyToManyField(blank=True, to='post.QuizQuestion'),
        ),
    ]
