# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20160430_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_model',
            name='teacher_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
