# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20160510_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answerField',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
