# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_videosection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosection',
            old_name='weekNo',
            new_name='weekNnumber',
        ),
    ]
