# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20160523_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userName',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
