# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_comments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsNo', models.CharField(max_length=20, null=True)),
                ('stdAmount', models.CharField(max_length=5)),
            ],
        ),
    ]
