# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_crstaken_crsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
