# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_comments_username2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='time',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userName2',
        ),
    ]
