# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20160606_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time2',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='userName2',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
