# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20160606_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userName2',
        ),
    ]
